### ISSUE TITLE
nomencl entries to the ToC does not respect KOMA-Script features

### ISSUE THREAD

**Issue by komascript** [borisveytsman/nomencl#3]
With option `intoc` package `nomencl` uses

    \addcontentsline{toc}{section}{\nomname}

or

    \addcontentsline{toc}{chapter}{\nomname}

to add the entry into the ToC. This is generally good but breaks features of KOMA-Script.

* KOMA-Script can align not-numbered entries into the ToC either left with the number of numbered entries or left with the text of numbered entries. To do so, not numbered entries need a `\nonumberline` in front of the text of not numbered entries. This is missing here. KOMA-Script provides `\addxcontentsline` to handle the difference of numbered and not numbered entries automatically. But `nomencl` does not use it, so the alignment of its ToC entry can be different.
*  KOMA-Script provides to write to a file with another extension instead of `toc`. To do so, it defines `\ext@toc` and allows to redefine it. This can be used, e.g., to add the sectioning headings of the appendix to a separated appendix ToC easily. But this does not work for `nomencl`'s ToC entry, because `nomencl` always writes to the file with extension `toc`.
* KOMA-Script adds one more user interface hierarchy of writing entries to the ToC: `\addparttocentry`, `\addchaptertocentry`, `\addsectiontocentry` etc. These commands do also handle not numbered entries. On chapter level it also handles extra gap to other lists, like LoF and LoT. And users can redefine them to change the content of the `toc`-file (resp. the `\ext@toc`-file). But such changes are ignored for the ToC entry of `nomencl` because it does not use `\addchaptertocentry` or `\addsectiontocentry`.

All these issues could be fixed by adding several extra code or much more simple by using package `tocbasic` like I've patched into (prior versions of) `nomencl` using `scrhack` and the hack file `nomencl.hak`, that you can find in KOMA-Script. This would also add additional features to `nomencl` without the need for a lot of extra code (there is even a [DTK](http://www.dante.de/DTK.html) article in DTK 4/2018 that explains more about this).

BTW: Good to see, that `nomencl` is maintained again.

**Comment by borisveytsman** [comment]
Could you please test the changes?

I am wary of using `tocbasic` by default since other users might find it incompatible.  Instead I detect whether the user loads `tocbasic` and patch `nomencl` accordingly.

**Comment by komascript** [comment]
It's better, but it does not work if either someone changes `\@inputfileextension` or uses compatibility option. I know `scrhack` has the same problem, but if you add the feature to `nomencl` maybe it would be better to change this.

And there is still a problem without `tocbasic` but with `article` and page style `headings` because the `\@mkboth` for this case is missing. Something `tocbasic` would have helped you to avoid (BTW: I find it a strange argument that `tocbasic` may result in incompatibility but using `etoolbox` and moreover `xkeyval`, that can break global options, and `ifthen` is used without any thoughts about incompatibility).

Attached is a patch, that solves these issues and also adds an option `automake` that automatically runs MakeIndex, so nobody needs to reconfigure his editor any longer. However this option cannot be used, e.g., with the multicol example, so it is not the default.

Feel free to use it or parts or modified parts of it. And let me know, if you do so, because I have to change `scrhack` again in such a case.

[nomencl.dtx.patch.txt](https://github.com/borisveytsman/nomencl/files/2802166/nomencl.dtx.patch.txt)
