### ISSUE TITLE
Typos in section 2.9.1 of the manual

### ISSUE THREAD

**Issue by quark67** [borisveytsman/nomencl#6]
The manual say:
> So, for example, if you want to separate constants and variables, you may use prefixes `c...` for constants and `v...` for variables,

and then suggest this code:
```
\renewcommand{\nomgroup}[1]{%
 \ifthenelse{\equal{#1}{R}}{\item[\textbf{Variables}]}{%
 \ifthenelse{\equal{#1}{G}}{\item[\textbf{Constants}]}{}}}
```

Why `{R}` and `{G}`? Aren't `{V}` and `{C}` more appropriate in this code?

(see lines 775-776 of https://github.com/borisveytsman/nomencl/blob/master/nomencl.dtx)

**Comment by borisveytsman** [comment]
Thanks!
